apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate-check
  namespace: 04-argo-rollout-metrics
spec:
  args:
  - name: stable-hash
  - name: canary-hash

  metrics:
  - name: error-rate
    interval: 30s
    count: 3
    successCondition: len(result) > 0 && result[0] < 0.05
    failureLimit: 3

    provider:
      prometheus:
        address: http://prometheus-stack-kube-prom-prometheus.default.svc.cluster.local:9090
        query: |
          (
            sum without(service, job) (
              rate(bad_responses_total{rollouts_pod_template_hash="{{args.canary-hash}}"}[1m])
            )
            /
            sum without(service, job) (
              rate(total_responses_total{rollouts_pod_template_hash="{{args.canary-hash}}"}[1m])
            )
          )