apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp-03
  namespace: 03-rollout-header-split-demo
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - 03-rollout-header-split-demo
  selector:
    matchLabels:
      app: myapp
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_rollouts_pod_template_hash]
          targetLabel: rollouts_pod_template_hash