apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp-simple
  namespace: ab-demo
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - ab-demo
  selector:
    matchLabels:
      app: myapp
  endpoints:
    - port: http
      path: /metrics
      interval: 15s